# Generated by Django 4.2.3 on 2023-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='method',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
